### PR TITLE
Net swipe

### PR DESCRIPTION
**Pull request by BenjyNotLikeTheDog**
I have the swiping feature working (the little blue line that SHOULD follow your cursor) as well as the scoring feature (1 per green blob you swipe). Just note, the game cannot be exited without actually refreshing or closing. I took out the red blobs that normally would've triggered a game over since we weren't doing anything like that. Is this how we want the swipe to work?

### CODE REVIEW

**Comment by jcandan** [comment]
hate to be a stickler, but the indentation throughout Game.js needs to be adjusted. most IDE and code editors come with the ability to reformat code, properly indenting and removing whitespace at the end of lines, etc. I'll take care of that real quick, but look into that on your end.

**Comment by jcandan** [comment]
notice something i did there, i added @todo comments. most IDE's come with a way to list all todo items in code. check out this plugin for brackets: https://github.com/mikaeljorhult/brackets-todo

**Comment by jcandan** [comment]
:+1:

**Comment by jcandan** [comment]
@BenjyBenton, is the comment on line 106, "Currently does not seem to be working", still valid? if so, that's fine given that it's already committed to master. Just curious on the status of this.

**Comment by Brent1798** [comment]
:+1:

**Pull request merged**
