### PR TITLE
adding the cut scene 

### PR DESCRIPTION
**Pull request by Brent1798**

### CODE REVIEW

**Comment by jcandan** [comment]
getting there. please change cutscene.js to CutScene.js. also modify the class name Game to CutScene within that file.

**Comment by jcandan** [comment]
see previous comments.  i know this is all pretty new, so no worries.

**Comment by jcandan** [comment]
made a few adjustments

**Comment by Brent1798** [comment]
looks good to me thanks.

**Comment by jcandan** [comment]
forgot to add in the library.

**Comment by jcandan** [comment]
i think it's ready. you can test the code locally: first pull the latest changes. then, change the initial state.start object in index.html:

`game.state.start('CutScene');`

That was my method of testing to ensure your code in this pull-request was valid. if you think all is well, please feel free to merge and delete.

**Pull request merged**
